# Generated by Django 3.1.2 on 2020-10-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remesh_core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='submission_time',
            new_name='start_date',
        ),
    ]
