# Generated by Django 3.1.2 on 2020-10-17 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remesh_core', '0005_auto_20201017_1709'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thoughts',
            new_name='Thought',
        ),
    ]
