# Generated by Django 3.1.2 on 2020-10-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remesh_core', '0006_auto_20201017_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='thoughts',
            new_name='thought',
        ),
    ]
