# Generated by Django 3.1.2 on 2020-10-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesh_core', '0007_auto_20201017_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
