# Generated by Django 3.1.2 on 2020-10-20 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remesh_core', '0008_auto_20201019_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
